from pathlib import Path
import shutil
p=Path(__file__).resolve().parents[1];out=p/'target/ar-ui-qa';out.mkdir(exist_ok=True)
for name in ['event-state.js','spatial.js','routes.js','style.css','community.css','spatial.css','product.css','experience.css','refinement.css','poyo-owl.svg','owl-mark.svg']:shutil.copyfile(p/'assets'/name,out/name)
page='''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AR操作のローカル検証</title>'''+''.join('<link rel="stylesheet" href="/'+n+'">' for n in ['style.css','community.css','spatial.css','product.css','experience.css','refinement.css'])+'''
<body class="cx-body"><main id="qa-main"></main><div id="poyo-root" class="cx-poyo"><button id="poyo-toggle" class="poyo-toggle" aria-label="ぽよと話す"><img src="/poyo-owl.svg" width="65"><span>ぽよと話す</span></button><section id="cx-poyo-panel" class="cx-poyo-panel" hidden><header><button id="cx-poyo-close" aria-label="アシストを閉じる">×</button></header><p>操作の模擬試験です。</p><textarea aria-label="ぽよへの質問"></textarea></section></div>
<script>Object.defineProperty(navigator,'userAgent',{value:'iPhone local UI test'});Object.defineProperty(navigator,'maxTouchPoints',{value:5});Object.defineProperty(document,'fullscreenEnabled',{value:false});navigator.mediaDevices.getUserMedia=async()=>new MediaStream();window.SpatialLocation={create:o=>({start(){o.onFix({lat:35.6802,lon:139.7671,accuracy:10});o.onStatus({active:true,phase:'tracking'});},stop(){o.onFix(null);}}),errorMessage:()=>''};window.google={maps:{Map:function(){},importLibrary:async()=>({Route:{computeRoutes:async q=>({routes:[{durationMillis:q.travelMode==='DRIVING'?60000:q.travelMode==='BICYCLING'?120000:300000,distanceMeters:111,warnings:[],path:[{lat:35.6802,lng:139.7671},{lat:35.6808,lng:139.7671},{lat:35.6812,lng:139.7671}],legs:[]}]})}})}};window.fetch=async()=>({json:async()=>({available:false,reason:'模擬試験では取得しません',links:[]})});</script>
<script src="/event-state.js"></script><script src="/routes.js"></script><script src="/spatial.js"></script><script>
const event={id:'venue',name:'検証用の会場',place:'東京駅',lat:35.6812,lon:139.7671,kind:'写真',start:new Date().toISOString(),end:new Date(Date.now()+3600000).toISOString()};document.querySelector('#qa-main').innerHTML=SpatialExplore.page();document.querySelector('#poyo-toggle').onclick=()=>{const root=document.querySelector('#poyo-root'),panel=document.querySelector('#cx-poyo-panel');panel.hidden=!panel.hidden;root.classList.toggle('open',!panel.hidden);};document.querySelector('#cx-poyo-close').onclick=()=>document.querySelector('#poyo-toggle').click();SpatialExplore.mount({getState:()=>({events:[event],following:[],google_maps_key:''}),esc:s=>String(s),go:()=>{},comment:()=>{},propose:()=>{},selected:'venue'});const camera=document.querySelector('#sx-camera'),start=camera.onclick;camera.onclick=async()=>{await start();const ev=new Event('deviceorientationabsolute');ev.absolute=true;ev.alpha=0;window.dispatchEvent(ev);};
setInterval(()=>{const ev=new Event('deviceorientationabsolute');ev.absolute=true;ev.alpha=359+Math.sin(Date.now()/1000)*.4;window.dispatchEvent(ev);},50);
</script></body></html>'''
(out/'index.html').write_text(page,encoding='utf-8');print(out)
