const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('../target/navigation-tools/node_modules/jsdom');
const dom=new JSDOM('<body class="cx-body"><main></main><div id="cx-toast"></div><div id="cx-nav"></div><nav id="cx-mobile-nav"></nav><div id="cx-account"></div><aside class="cx-side"><a href="#">メニュー項目</a></aside><button data-ui-nav>メニュー</button></body>',{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
const asset=name=>fs.readFileSync(path.join(__dirname,'../assets',name),'utf8');
w.eval(asset('inbox.js'));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={me:{id:'a'},accounts:[],rooms:[{id:'r',name:'写真さんぽ',kind:'group',members:['a','b'],member_count:2,latest_at:100,latest_talk:'明日は入口で',unread:101},{id:'h',name:'hidden',list_state:'hidden',kind:'dm',members:['a','b'],latest_at:200}],alerts:[{id:'a1',name:'会場変更',at:100,priority:3,event:'e',changed:['place']},{id:'a2',name:'Talk',at:200,priority:1,room:'r'}],events:[],following:[]},calls=[],lastGo=null;
let inbox;const c={state:()=>state,esc,route:(view,id='')=>`/?view=${view}&id=${encodeURIComponent(id)}`,avatar:()=>'<span class="cx-avatar">A</span>',account:()=>null,mutate:async(op,v)=>{calls.push({op,...v});if(op==='inbox_item'){(v.kind==='room'?state.rooms:state.alerts).find(x=>x.id===v.id).list_state=v.state;}else if(op==='ack_alert')state.alerts.find(x=>x.id===v.id).read_at=1;},render:()=>{w.document.querySelector('main').innerHTML=inbox.rooms('r')+inbox.alerts();},go:(v,id)=>lastGo={v,id},toast:t=>w.document.querySelector('#cx-toast').textContent=t};
inbox=w.SpatialInbox(c);c.render();const $=s=>w.document.querySelector(s),tick=()=>new Promise(r=>setImmediate(r));
const pointer=(node,type,x,y,id=1)=>{const e=new w.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{pointerType:'touch',pointerId:id,clientX:x,clientY:y});node.dispatchEvent(e);return e;};
const key=(el,key,more={})=>el.dispatchEvent(new w.KeyboardEvent('keydown',{key,bubbles:true,cancelable:true,...more}));
(async()=>{
assert.equal(inbox.firstRoom().id,'r');assert.equal($('.ib-badge').textContent,'99+');assert.equal($('.ib-members').textContent,'(2)');assert(!$('.ib-row[data-inbox-id=h]'));
assert.equal($('.ib-notifications .ib-row').dataset.inboxId,'a1','important changes precede newer Talk');
const retained=$('[data-inbox-id=r]');retained.querySelector('.ib-main').focus();state.rooms[0].unread=0;inbox.refresh();assert.equal($('[data-inbox-id=r]'),retained,'read acknowledgement retains a focused row');assert(!retained.querySelector('.ib-badge'));state.rooms[0].unread=101;inbox.refresh();assert.equal(retained.querySelector('.ib-badge').textContent,'99+');
let row=$('[data-inbox-id=r]'),face=row.querySelector('.ib-main');pointer(face,'pointerdown',250,60);pointer(face,'pointermove',100,65);pointer(face,'pointerup',100,65);assert(row.classList.contains('ib-revealed'));assert.equal(calls.length,0,'swipe cannot delete data');
row.querySelector('[data-inbox-action=deleted]').click();await tick();assert.equal(state.rooms[0].list_state,'deleted');assert.equal(calls[0].op,'inbox_item');assert.equal(state.rooms[0].latest_talk,'明日は入口で');assert(!$('[data-inbox-id=r]'));
$('[data-inbox-undo]').click();await tick();assert.equal(state.rooms[0].list_state,'visible');
let filter=$('[data-inbox-filter=room]');filter.value='hidden';filter.dispatchEvent(new w.Event('change',{bubbles:true}));assert($('[data-inbox-id=h]'));assert(!$('[data-inbox-id=r]'));$('[data-inbox-id=h] [data-inbox-menu]').click();$('.ib-context-menu [data-inbox-action=visible]').click();await tick();assert.equal(state.rooms[1].list_state,'visible');
filter=$('[data-inbox-filter=room]');filter.value='visible';filter.dispatchEvent(new w.Event('change',{bubbles:true}));row=$('[data-inbox-id=r]');face=row.querySelector('.ib-main');pointer(face,'pointerdown',250,60);pointer(face,'pointermove',240,130);pointer(face,'pointerup',240,130);assert(!row.classList.contains('ib-revealed'),'vertical scroll remains vertical');
pointer(face,'pointerdown',250,60);pointer(face,'pointermove',100,65);pointer(face,'pointercancel',100,65);assert(!row.classList.contains('ib-revealed'),'cancel restores row');
row.dispatchEvent(new w.MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:150,clientY:100}));assert.equal($('.ib-context-menu').getAttribute('role'),'menu');key(w.document.activeElement,'ArrowDown');assert.equal(w.document.activeElement.dataset.inboxAction,'deleted');key(w.document.activeElement,'Escape');assert(!$('.ib-context-menu'));assert.equal(w.document.activeElement,row.querySelector('.ib-more'));
key(row.querySelector('.ib-main'),'F10',{shiftKey:true});assert($('.ib-context-menu'));key(w.document.activeElement,'Escape');
const search=$('[data-inbox-search-input]');search.value='写真';search.dispatchEvent(new w.Event('input',{bubbles:true}));assert(!$('[data-inbox-id=r]').hidden);assert($('[data-inbox-id=h]').hidden);
search.blur();inbox.refresh();assert.equal($('[data-inbox-search-input]').value,'写真','background read updates preserve the search');const cleared=$('[data-inbox-search-input]');cleared.value='';cleared.dispatchEvent(new w.Event('input',{bubbles:true}));assert(!$('[data-inbox-id=h]').hidden,'clearing a preserved query restores all rows');
// Let the intentional swipe-click suppression expire before exercising alert navigation.
await new Promise(r=>setTimeout(r,320));$('[data-inbox-open=a2]').click();await tick();assert.deepEqual(lastGo,{v:'messages',id:'r'});assert.equal(state.alerts[1].read_at,1);
// Source/user-controlled labels remain escaped, including attribute fields.
state.rooms[0].name='<img src=x onerror=alert(1)>';c.render();assert(!$('.ib-copy img'));assert($('[data-inbox-id=r] .ib-copy').textContent.includes('<img'));
w.eval(asset('experience.js'));const ui=w.SpatialUI({...c,view:()=> 'messages',selected:()=>'',readPref:()=>'',relative:()=>'',richText:esc});ui.shell();const links=[...$('#cx-mobile-nav').children];assert.equal(links.length,7);assert(links[3].classList.contains('ui-mobile-create'));assert(links[3].href.includes('view=create'));assert.equal(links[3].getAttribute('aria-label'),'イベントを作成');
state.rooms[0].list_state='hidden';ui.shell();assert(!$('#cx-mobile-nav a[href*="messages"] .ui-unread'),'hidden room excluded from navigation unread badge');
$('[data-ui-nav]').click();assert(w.document.body.classList.contains('ui-nav-open'));const drawer=$('.cx-side');pointer(drawer,'pointerdown',220,60);pointer(drawer,'pointermove',110,65);assert(w.document.body.classList.contains('ui-nav-dragging'));pointer(drawer,'pointerup',110,65);assert(!w.document.body.classList.contains('ui-nav-open'));assert.equal($('[data-ui-nav]').getAttribute('aria-expanded'),'false');
$('[data-ui-nav]').click();pointer(drawer,'pointerdown',220,60);pointer(drawer,'pointermove',215,130);pointer(drawer,'pointerup',215,130);assert(w.document.body.classList.contains('ui-nav-open'),'vertical sidebar scrolling must not close it');
console.log('PASS inbox: touch reveal/cancel/vertical scroll, no destructive full swipe, personal deletion/undo/restore, context menu and keyboard, priority, unread badges, escaping, search, centered creation and drawer swipe');
dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
